language: python

env:
  - DJANGO=1.7

python:
 - "2.7"

install:
 - sudo apt-get install python2.7 python-pip python-dev
 - sudo pip install python-Levenshtein
 - pip install -r requirements.txt
 - for i in configuration/*.py.template; do cp $i "${i/.py.template/.py}"; done

before_script:
 - python manage.py makemigrations
 - python manage.py migrate

script:
 - coverage run manage.py test
# - python manage.py harvest
 - coveralls

notifications:
  slack: busine-me:a8LjiirRLvRz4gsfIbvNXMWR#mds
